
# rvmrc
run 'echo "rvm_trust_rvmrcs=1" > .rvmrc'
run 'echo "rvm `rvm-prompt`" >> .rvmrc'

# .gitignore
file_append '.gitignore', open("#{SOURCE}/gitignore").read
git :init
git :add => '.gitignore'

#
# Remove some files generated by Rails
#
# ujs will be replaced with the jquery version later
run 'rm -f public/javascripts/rails.js'
run 'rm -f public/images/rails.png'
run 'rm -f config/database.template.yml'
run "rm -f app/views/layouts/application.html.erb"
git :add => "."
git :commit => "-am 'initial commit'"

#
# Add staging env
#
inside('config/environments') do
  run 'cp development.rb staging.rb'
end
git :add => "."
git :commit => "-am 'added staging environment'"