# use this for local installs
SOURCE=ENV['SOURCE'] || 'http://github.com/jeanmartin/strappy/raw/master'

def gen(what)
  generate what
end

def file_append(file, data)
  log :append, file
  File.open(file, 'a') {|f| f.write(data) }
end

def file_inject(file_name, sentinel, string, before_after=:after)
  log :inject, file_name
  gsub_file file_name, /(#{Regexp.escape(sentinel)})/mi do |match|
    if :after == before_after
      "#{match}\n#{string}"
    else
      "#{string}\n#{match}"
    end
  end
end

def file_str_replace(file_name, sentinel, replacement)
  log :gsub, file_name
  gsub_file file_name, /(#{Regexp.escape(sentinel)})/mi do |match|
    replacement
  end
end


#
# Ask some questions
#
puts "\n#{'*' * 80}\n"
puts "Please answer the following questions with either yes [y] or no [n]"
puts "#{'*' * 80}\n\n"
want_newrelic   = yes?("Do you want New Relic?")
want_geocoding  = yes?("Do you want geocoding (using geocoder)?")
want_puret      = yes?("Do you want model translations (using puret)?")
want_paperclip  = yes?("Do you want file uploads (using paperclip)?")
want_ssl        = yes?("Do you want SSL (ssl_requirement plugin)?")
want_am         = yes?("Do you want online payment (using active_merchant)?")
want_couchdb    = yes?("Do you want to use CouchDB (using simply_stored)?")
want_jspec      = yes?("Do you want JavaScript tests (using JSpec)?")
puts "\n#{'*' * 80}\n\n"

puts "\n#{'*' * 80}\n"
puts "Some information about your application, please"
puts "#{'*' * 80}\n\n"
app_name        = `pwd`.split('/').last.strip
puts "Your app shortname is '#{app_name}'"
app_fullname    = ask("Please enter the full name [#{app_name.capitalize}]:") || app_name.capitalize
app_fullname    = app_fullname.blank? ? app_name.capitalize : app_fullname
db_user   = ask("MySQL username [root]:")
db_user   = db_user.blank? ? 'root' : db_user
db_pw     = ask("MySQL password []:")
puts "\n#{'*' * 80}\n\n"



# .gitignore
file_append '.gitignore', open("#{SOURCE}/gitignore").read
git :init
git :add => '.gitignore'


#
# Remove some files generated by Rails
#
# ujs will be replaced with the jquery version later
run 'rm -f public/javascripts/rails.js'
run 'rm -f public/images/rails.png'
run 'rm -f config/database.template.yml'
run "rm -f app/views/layouts/application.html.erb"
git :add => "."
git :commit => "-am 'initial commit'"


#
# Add staging env
#
inside('config/environments') do
  run 'cp development.rb staging.rb'
end
git :add => "."
git :commit => "-am 'added staging environment'"


#
# Database config
#
file 'config/database.yml', 
%Q{
development:
  adapter: mysql2
  database: #{app_name}_development
  username: #{db_user}
  password: #{db_pw}
  host: localhost
  encoding: utf8
 
test:
  adapter: mysql2
  database: #{app_name}_test
  username: #{db_user}
  password: #{db_pw}
  host: localhost
  encoding: utf8
 
staging:
  adapter: mysql2
  database: #{app_name}_staging
  username: #{app_name}
  password:
  host: localhost
  encoding: utf8
  socket: /var/lib/mysql/mysql.sock
 
production:
  adapter: mysql2
  database: #{app_name}
  username: #{app_name}
  password:
  host: localhost
  encoding: utf8
  socket: /var/lib/mysql/mysql.sock
}
git :add => "."
git :commit => "-am 'added database.yml'"


# install Gemfile and gems
run 'rm Gemfile'
file 'Gemfile', <<-EOGEMS
source 'http://rubygems.org'
source 'http://gems.github.com'

gem 'rails', '>= 3.0.0'
gem 'authlogic', :git => 'http://github.com/ochko/authlogic.git'
gem 'capistrano', '2.5.19'
gem 'capistrano-ext', '1.2.1'
gem 'config_reader', :git => 'git://github.com/jeanmartin/config_reader-gem.git'
gem 'friendly_id', '>=3.1.3'
gem "formtastic", :git => "git://github.com/justinfrench/formtastic.git", :branch => "rails3"
gem 'compass', '>= 0.10.5'
gem 'html5-boilerplate', :git => 'git://github.com/sporkd/compass-html5-boilerplate.git'
gem 'haml', '>=3.0.18'
gem 'hoe', '>=2.6.1'
gem 'mongrel'
gem 'mysql2'
gem 'hpricot'
gem 'factory_girl_rails'
gem 'spork'
gem 'rspec-rails', '>= 2.0.0.beta.20'
gem 'will_paginate', :git => 'http://github.com/mislav/will_paginate.git', :branch => 'rails3'
#{"gem 'jspec'" if want_jspec}
#{"gem 'paperclip'" if want_paperclip}
#{"gem 'puret', :git => 'git://github.com/jo/puret.git'" if want_puret}
#{"gem 'simply_stored'" if want_couchdb}
#{"gem 'activemerchant', :git => 'git://github.com/Shopify/active_merchant.git'" if want_am}
#{"gem 'newrelic_rpm', '>=2.13.0.beta5'" if want_newrelic}

group :development do
  gem 'rails3-generators'
  gem 'haml-rails'
  gem 'jquery-rails'
end

group :test do
  gem 'capybara'
  gem 'cucumber'
  gem 'cucumber-rails'
  gem 'database_cleaner', :git => 'git://github.com/bmabey/database_cleaner.git'
  gem 'faker'
  gem 'launchy'
  gem 'pickle'
  gem 'rcov'
  gem 'webrat'
  gem 'shoulda'
  gem 'rspec-rails', '>= 2.0.0.beta.20'
  gem 'ZenTest'
  gem 'autotest-growl'
end
EOGEMS

run 'bundle install'
git :add => "."
git :commit => "-am 'added Gemfile, installed gems'"



#
# Plugins (with patches)
#

# dynamic_form
plugin 'dynamic_form', :git => 'git://github.com/rails/dynamic_form.git'

# Geocoding
plugin 'geocoder', :git => 'git://github.com/chenillen/geocoder.git' if want_geocoding

# Bootstrapper
plugin 'bootstrapper', :git => 'git://github.com/jeanmartin/bootstrapper.git'
file 'db/bootstrap.rb', <<-EOF
Bootstrapper.for :development do |b|
  b.truncate_tables :users

  Factory(:admin)
end

Bootstrapper.for :production do |b|
end

Bootstrapper.for :test do |b|
end

Bootstrapper.for :staging do |b|
end
EOF
git :add => "."
git :commit => "-am 'installed Bootstrapper plugin'"



#
# Generators and patches
#

# factory_girl
file_inject('config/application.rb',
  '# config.action_view.javascript_expansions[:defaults] = %w(jquery rails)',
  "
    config.generators do |g|
      g.fixture_replacement   :factory_girl, :dir => 'spec/factories'
    end",
  :after)
git :add => "."
git :commit => "-am 'installed factory_girl'"

# jquery-rails
gen 'jquery:install --ui'
git :add => '.'
git :commit => "-am 'installed jQuery (+UI)'"

run 'echo N\n | haml --rails .'
run 'mkdir -p public/stylesheets/sass'
git :add => "."
git :commit => "-am 'initialized Haml and Sass'"

# JSpec
if want_jspec
  run 'jspec init --rails'
  git :add => '.'
  git :commit => '-am "installed JSpec"'
end

# SSL
if want_ssl
  plugin 'ssl_requirement', :git => 'git://github.com/rails/ssl_requirement.git'
  git :add => '.'
  git :commit => '-am "installed SSL support (ssl_requirement plugin)"'
end

# simply_stored
if want_couchdb
  file 'config/couchdb.yml', <<-EOF
development: #{app_name}
test:  #{app_name}_test
production: http://db.server/#{app_name}
EOF
  initializer 'simply_stored.rb', <<-EOF
require 'simply_stored/couch'  
CouchPotato::Config.database_name = '#{app_name}'
EOF
  git :add => '.'
  git :commit => '-am "installed CouchDB support (via simply_stored)"'
end

# friendly_id
gen 'friendly_id'

# Formtastic
gen 'formtastic:install'
initializer 'formtastic.rb', <<-CODE
# Set the default text field size when input is a string. Default is 50.
# Formtastic::SemanticFormBuilder.default_text_field_size = 50

# Set the default text area height when input is a text. Default is 20.
# Formtastic::SemanticFormBuilder.default_text_area_height = 5

# Should all fields be considered "required" by default?
# Defaults to true, see ValidationReflection notes below.
# Formtastic::SemanticFormBuilder.all_fields_required_by_default = true

# Should select fields have a blank option/prompt by default?
# Defaults to true.
# Formtastic::SemanticFormBuilder.include_blank_for_select_by_default = true

# Set the string that will be appended to the labels/fieldsets which are required
# It accepts string or procs and the default is a localized version of
# '<abbr title="required">*</abbr>'. In other words, if you configure formtastic.required
# in your locale, it will replace the abbr title properly. But if you don't want to use
# abbr tag, you can simply give a string as below
# Formtastic::SemanticFormBuilder.required_string = "(required)"

# Set the string that will be appended to the labels/fieldsets which are optional
# Defaults to an empty string ("") and also accepts procs (see required_string above)
# Formtastic::SemanticFormBuilder.optional_string = "(optional)"

# Set the way inline errors will be displayed.
# Defaults to :sentence, valid options are :sentence, :list and :none
# Formtastic::SemanticFormBuilder.inline_errors = :sentence

# Set the method to call on label text to transform or format it for human-friendly
# reading when formtastic is used without object. Defaults to :humanize.
# Formtastic::SemanticFormBuilder.label_str_method = :humanize

# Set the array of methods to try calling on parent objects in :select and :radio inputs
# for the text inside each @<option>@ tag or alongside each radio @<input>@. The first method
# that is found on the object will be used.
# Defaults to ["to_label", "display_name", "full_name", "name", "title", "username", "login", "value", "to_s"]
# Formtastic::SemanticFormBuilder.collection_label_methods = [
#   "to_label", "display_name", "full_name", "name", "title", "username", "login", "value", "to_s"]

# Formtastic by default renders inside li tags the input, hints and then
# errors messages. Sometimes you want the hints to be rendered first than
# the input, in the following order: hints, input and errors. You can
# customize it doing just as below:
# Formtastic::SemanticFormBuilder.inline_order = [:input, :hints, :errors]

# Specifies if labels/hints for input fields automatically be looked up using I18n.
# Default value: false. Overridden for specific fields by setting value to true,
# i.e. :label => true, or :hint => true (or opposite depending on initialized value)
Formtastic::SemanticFormBuilder.i18n_lookups_by_default = true

# You can add custom inputs or override parts of Formtastic by subclassing SemanticFormBuilder and
# specifying that class here.  Defaults to SemanticFormBuilder.
# Formtastic::SemanticFormHelper.builder = MyCustomBuilder
CODE
git :add => "."
git :commit => "-am 'installed formtastic'"

# authlogic
gen 'authlogic:session user_session'
run 'rm spec/models/user_session_spec.rb'
run 'rm test/factories/user_sessions.rb'
file_inject('app/models/user_session.rb',
  'class UserSession < Authlogic::Session::Base',
  '  find_by_login_method :find_by_login_or_email

  def persisted?; false; end',
  :after)
git :add => "."
git :commit => "-am 'installed authlogic'"

# RSpec
gen 'rspec:install'
file_append('spec/spec_helper.rb', open("#{SOURCE}/spec/helpers.rb").read)
git :add => "."
git :commit => "-am 'installed RSpec'"

# Cucumber
gen 'cucumber:install --rspec --capybara'
git :add => "."
git :commit => "-am 'installed Cucumber'"

# pickle
gen 'pickle --paths --email --force'
file_inject('features/support/paths.rb',
  "'/'", "
    when /forgot password/
      forgot_password_path
    when 'the login page'
      login_path
    when 'the signup page'
      signup_path
    when 'the admin page'
      admin_path
    when 'the account page'
      account_path
    when 'the account edit page'
      edit_user_path(@user)
",
  :after)
file_inject('features/support/email.rb',
  '# add your own name => email address mappings here',
  '    when /the user/
      @user.try(:email) || @current_user.try(:email)',
  :after
)
git :add => "."
git :commit => "-am 'installed pickle support to cucumber'"

# enable authlogic in cucumber
file_inject('spec/spec_helper.rb',
  "require 'rspec/rails'",
  "require 'authlogic/test_case'

include Authlogic::TestCase",
  :after)
git :add => "."
git :commit => "-am 'added authlogic to RSpec'"







#
# use compass to bootstrap the html5 boilerplate
#
run 'bundle exec compass init rails -r html5-boilerplate -u html5-boilerplate --sass-dir public/stylesheets/sass/ --css-dir public/stylesheets/ --force -q'
file 'app/views/layouts/_header.html.haml',
  open("#{SOURCE}/app/views/layouts/_header.html.haml").read
git :add => "."
git :commit => "-am 'Added HTML5 Layout and templates'"

# patch javascript(-includes)

# remove jquery-1.4.2.min.js since we already got jquery.min.js
run 'rm public/javascripts/jquery-1.4.2.min.js'

# add i18n & application js file(s)
file "public/javascripts/application.js", open("#{SOURCE}/public/javascripts/application.js").read
file 'public/javascripts/jquery-ui-i18n.min.js', open('http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.2/i18n/jquery-ui-i18n.min.js').read

# include formtastic stylesheets
file_str_replace('app/views/layouts/_stylesheets.html.haml',
  "= stylesheet_link_tag 'style', :media => 'all'",
  "= stylesheet_link_tag 'style', 'formtastic', :media => 'all', :cache => 'all'"
)
# include jquery ui
file_inject('app/views/layouts/_javascripts.html.haml',
 'google.load("jquery", "1.4.2");',
 '    google.load("jqueryui", "1.8.4");',
  :after
)
file_str_replace('app/views/layouts/_javascripts.html.haml',
  '= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"',
  '= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.2/jquery-ui.min.js", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.2/i18n/jquery-ui-i18n.min.js"'
)
# include blackbird
file_inject('app/views/layouts/_javascripts.html.haml',
  '!window.jQuery && document.write(\'#{ escape_javascript(javascript_include_tag "jquery-1.4.2.min") }\')',
  "\n= blackbird_tags.html_safe",
  :after
)
file_str_replace('app/views/layouts/_javascripts.html.haml',
  '!window.jQuery && document.write(\'#{ escape_javascript(javascript_include_tag "jquery-1.4.2.min") }\')',
  '!window.jQuery && document.write(\'#{ escape_javascript(javascript_include_tag "jquery.min", "jquery-ui.min", "jquery-ui-i18n.min", :cache => "jquery_all") }\')'
)
file_str_replace('app/views/layouts/_javascripts.html.haml',
  "= javascript_include_tag 'rails', 'plugins', 'application'",
  "= javascript_include_tag 'rails', 'plugins', 'application', :cache => 'all'"
)
# remove yui profiler and profileviewer
run 'rm -rf public/javascripts/profiling'
file_str_replace('app/views/layouts/_javascripts.html.haml', "-# yui profiler and profileviewer", '')
file_str_replace('app/views/layouts/_javascripts.html.haml', "- if Rails.env == 'development'", '')
file_str_replace('app/views/layouts/_javascripts.html.haml', "  = javascript_include_tag 'profiling/yahoo-profiling.min', 'profiling/config'", '')
# don't overwrite blackbirds log function
file_str_replace('public/javascripts/plugins.js',
  'window.log = function(){',
  'window.clog = function(){'
)
git :add => "."
git :commit => "-am 'Added custom js and js patches'"




#
#  Add our own scaffolding
#

route <<-EOROUTES
  root :to => 'home#index'

  match 'admin',
    :as => :admin,
    :to => 'admin/base#index'

  match 'login',
    :as => :login,
    :to => 'user_sessions#new'

  match 'logout',
    :as => :logout,
    :to => 'user_sessions#destroy'

  match 'signup',
    :as => :signup,
    :to => 'users#new'

  match 'forgot_password',
    :as => :forgot_password,
    :to => 'password_resets#new'

  resource :account, :controller => "users"
  resource :user_session

  resources :password_resets
  resources :users
EOROUTES

# user & user_sessions
gen 'controller user_sessions'
gen 'scaffold user'
# get rid of the gend templates
Dir.glob('app/views/users/*.erb').each do |file|
  run "rm #{file}"
end
# and the route specs (they are flawed)
run 'rm spec/routing/users_routing_spec.rb'
git :add => "."
git :commit => "-am 'installed user and session management'"

# use our user migration
file Dir.glob('db/migrate/*_create_users.rb').first,
  open("#{SOURCE}/db/migrate/create_users.rb").read
git :add => "."
git :commit => "-am 'installed custom user migration'"

# password resetting
gen 'controller password_resets'

# model
%w( user notifier ).each do |name|
  file "app/models/#{name}.rb",
    open("#{SOURCE}/app/models/#{name}.rb").read
end

# controllers
%w( user_sessions password_resets users ).each do |name|
  file "app/controllers/#{name}_controller.rb",
    open("#{SOURCE}/app/controllers/#{name}_controller.rb").read
end

# views
%w(
  notifier/password_reset_instructions.text.erb
  password_resets/edit.html.haml
  password_resets/new.html.haml
  user_sessions/new.html.haml
  users/_form.haml
  users/edit.html.haml
  users/new.html.haml
  users/show.html.haml
).each do |name|
  file "app/views/#{name}", open("#{SOURCE}/app/views/#{name}").read
end
git :add => "."
git :commit => "-am 'installed models, controllers and views'"


# Add ApplicationController
file 'app/controllers/application_controller.rb',
  open("#{SOURCE}/app/controllers/application_controller.rb").read
# Add ApplicationHelper
file 'app/helpers/application_helper.rb',
  open("#{SOURCE}/app/helpers/application_helper.rb").read
git :add => "."
git :commit => "-am 'added ApplicationHelper and -Controller'"

# Remove index.html and add HomeController
git :rm => 'public/index.html'
gen 'controller home'
file 'app/views/home/index.html.haml',
  open("#{SOURCE}/app/views/home/index.html.haml").read
file "app/helpers/home_helper.rb",
  open("#{SOURCE}/app/helpers/home_helper.rb").read
file "spec/controllers/home_controller_spec.rb",
  open("#{SOURCE}/spec/controllers/home_controller_spec.rb").read
git :add => "."
git :commit => "-am 'Removed index.html. Added HomeController'"

# Add Action images
%w(
  add.png
  arrow_up_down.png
  delete.png
  pencil.png
  user_edit.png
).each do |name|
  file "public/images/icons/#{name}",
    open("#{SOURCE}/public/images/icons/#{name}").read
end
git :add => "."
git :commit => "-am 'Added Action images'"

# setup admin section
run "cp app/views/layouts/application.html.haml app/views/layouts/admin.html.haml"
file_str_replace('app/views/layouts/admin.html.haml',
  "= render :partial => 'layouts/header'",
  "= render :partial => 'layouts/admin_header'")
file 'app/views/layouts/_admin_header.html.haml',
  open("#{SOURCE}/app/views/layouts/_admin_header.html.haml").read
%w(
  app/controllers/admin
  app/views/admin/base
  spec/controllers/admin
  app/helpers/admin
).each do |dir|
  run "mkdir -p #{dir}"
end
file "app/views/admin/base/index.html.haml",
  open("#{SOURCE}/app/views/admin/base/index.html.haml").read
file "app/controllers/admin/base_controller.rb",
  open("#{SOURCE}/app/controllers/admin/base_controller.rb").read
file "spec/controllers/admin/base_controller_spec.rb",
  open("#{SOURCE}/spec/controllers/admin/base_controller_spec.rb").read
file "app/helpers/admin/base_helper.rb",
  open("#{SOURCE}/app/helpers/admin/base_helper.rb").read
git :add => "."
git :commit => "-am 'Added admin stubs'"

# Add in the :xhr mime type
file_inject('config/initializers/mime_types.rb',
  '# Be sure to restart your server when you modify this file.',
  'Mime::Type.register_alias "text/html", :xhr',
  :after
)
git :add => "."
git :commit => "-am 'added :xhr mime type'"

# update the readme
run 'rm README'
file 'README.textile', open("#{SOURCE}/README.textile").read
git :add => "."
git :commit => "-am 'Replaced README'"



#
# Install custom files and patches
#

# Blackbird
run 'mkdir -p public/blackbird'
file 'public/blackbird/blackbird.js',
  open('http://blackbirdjs.googlecode.com/svn/trunk/blackbird.js').read
file 'public/blackbird/blackbird.css',
  open('http://blackbirdjs.googlecode.com/svn/trunk/blackbird.css').read
file 'public/blackbird/blackbird.png',
  open('http://blackbirdjs.googlecode.com/svn/trunk/blackbird.png').read
git :add => "."
git :commit => "-am 'installed Blackbird'"

# strappy rake tasks
rakefile 'strappy.rake', open("#{SOURCE}/lib/tasks/strappy.rake").read
git :add => "."
git :commit => "-am 'Added strappy rake file'"

# SiteConfig
file 'config/site.yml', <<-EOF
defaults:
  site_url: http://localhost:3000/
  host_name: #{app_name}.com
  mail_from: noreply@#{app_name}.com
  site_name: #{app_fullname}
  admin_email: admin@#{app_name}.com
  blackbird: true

production:
  site_url: http://#{app_name}.com
  blackbird: false

test:
  blackbird: false

EOF
initializer 'site_config.rb', open("#{SOURCE}/lib/site_config.rb").read
git :add => "."
git :commit => "-am 'added SiteConfig'"

# factories
run 'mkdir -p spec/factories'
%w( users ).each do |name|
  file "spec/factories/#{name}.rb", open("#{SOURCE}/spec/factories/#{name}.rb").read
end
git :add => "."
git :commit => "-am 'added factories'"

# features
%w(
  admin/admin_base.feature
  application/application_base.feature
  home/home.feature
  users/users.feature
  step_definitions/_common_steps.rb
  step_definitions/_custom_web_steps.rb
  step_definitions/user_steps.rb
).each do |name|
  file "features/#{name}", open("#{SOURCE}/features/#{name}").read
end
git :add => "."
git :commit => "-am 'added features'"

# spork
run 'spork --bootstrap'
git :add => "."
git :commit => "-am 'Bootstrapped spork'"

# Capistrano
capify!
file 'config/deploy.rb', open("#{SOURCE}/config/deploy.rb").read
%w( production staging ).each do |env|
  file "config/deploy/#{env}.rb", <<-EOC
set :rails_env, "#{env}"
set :branch, "#{env}"
EOC
end
git :add => "."
git :commit => "-am 'added Capistrano config'"


# TODO add cruise control task(s)

# # CC.rb
# rakefile('cruise.rake') { open("#{SOURCE}/lib/tasks/cruise.rake").read }
# git :add => "."
# git :commit => "-am 'Added cruise rake task'"




#
# cleanup
#

run 'rm -rf test'
# clear helper specs
inside('spec/helpers') do
  run 'rm -rf *'
end
# clear view specs
inside('spec/views') do
  run 'rm -rf *'
end
# clear request specs
inside('spec/requests') do
  run 'rm -rf *'
end
run 'rm spec/models/user_session_spec.rb'
git :add => '.'
git :commit => '-am "cleanup"'
run 'mkdir -p spec/fixtures'
%w(
  fixtures/users.yml
  helpers/application_helper_spec.rb
  controllers/password_resets_controller_spec.rb
  controllers/user_sessions_controller_spec.rb
  controllers/users_controller_spec.rb
  models/user_spec.rb
).each do |name|
  file "spec/#{name}", open("#{SOURCE}/spec/#{name}").read
end
git :add => '.'
git :commit => "-am 'added specs'"



# migrate
rake('db:migrate')
git :add => "."
git :commit => "-am 'migrated'"

# bootstrap
rake 'db:bootstrap'

#
# done!
#

puts "\n#{'*' * 80}\n\n"
puts "Final Notes:"
puts "\n#{'*' * 80}\n\n"
puts "If you want to use autotest call:"
puts "#> bundle exec autotest"
puts "(or to enable cucumber:)"
puts "#> AUTOFEATURE=true bundle exec autotest"
puts
puts "I recommend the following ~/.autotest file (at least on OS X):"
puts "require 'autotest/growl'

Autotest::Growl::image_dir = 'ampelmaennchen'
Autotest::Growl::clear_terminal = false

Autotest.add_hook(:initialize) {|at|
  %w{.DS_store db log rerun.txt}.each { |e| at.add_exception(e) }
  at.add_exception %r{^\.git}  # ignore Version Control System
  at.add_exception %r{^./tmp}  # ignore temp files, lest autotest will run again, and again...
  #at.clear_mappings         # take out the default (test/test*rb)
  at.add_mapping(%r{^lib/.*\.rb$}) {|f, _|
    Dir['spec/**/*.rb']
  }
  nil
}"
puts "\n#{'*' * 80}\n\n"
puts "All done. Enjoy."
puts "\n#{'*' * 80}\n\n"
