# specify an alternate gems repository
# source: http://local_mirror.example.com
# specify a different gem command
# gem_command: 'jruby -S gem'
gems:
  # - name: postgres
  #   # the version to use
  #   version: '0.7.1'
  #   # use a specfic source URL
  #   source: 'http://mongrel.rubyforge.org/releases'
  #   # load with GemTools.load_gems
  #   load: true
  #   # any extra config that needs to be passed to gem install
  #   config: '--with-pgsql-include-dir=/usr/local/pgsql/include --with-pgsql-lib-dir=/usr/local/pgsql/lib'
  #   # require name is different than the gem name
  #   require_name: foo-bar

  - name: 'rails'
    version: '2.3.5'

  - name: 'config_reader'
    version: '0.0.6'
    load: true

  - name: 'cucumber'
    version: '0.6.2'

  - name: 'cucumber-rails'
    version: '0.2.4'

  - name: 'database_cleaner'
    version: '0.4.3'

  - name: 'launchy'
    version: '0.3.5'

  - name: 'rspec'
    version: '1.3.0'

  - name: 'rspec-rails'
    version: '1.3.2'

  - name: 'webrat'
    version: '0.7.0'

  - name: 'email_spec'
    version: '0.4.0'

  - name: 'machinist'
    version: '1.0.6'

  - name: 'faker'
    version: '0.3.1'

  - name: 'haml'
    version: '2.2.17'

  - name: 'rcov'
    version: '0.9.7.1'

  - name: 'capistrano'
    version: '2.5.14'

  - name: 'capistrano-ext'
    version: '1.2.1'

  - name: 'seed-fu'
    version: '1.2.3'
    load: true

  - name: 'will_paginate'
    version: '2.3.12'
    load: true

  - name: 'authlogic'
    version: '2.1.3'
    load: true

  - name: 'friendly_id'
    version: '2.2.7'
    load: true
